steps:
- powershell: >
    Write-Host (
    '##vso[task.setvariable variable=LayoutCmd]&
    "{0}"
    "{1}\PC\layout"
    -vv
    --source "{1}"
    --build "{2}"
    --temp "{3}"
    --include-cat "{2}\python.cat"
    --doc-build "{4}"'
    -f (
    "$(PYTHON)",
    "$(Build.SourcesDirectory)",
    (Split-Path -Parent "$(PYTHON)"),
    "$(Build.BinariesDirectory)\layout-temp",
    "$(Build.BinariesDirectory)\doc"
    ))
  displayName: 'Set LayoutCmd'
