jobs:
- job: Make_Nuget_Layout
  displayName: Make Nuget layout
  condition: and(succeeded(), eq(variables['DoNuget'], 'true'))

  pool:
    vmName: win2016-vs2017

  workspace:
    clean: all

  strategy:
    matrix:
      win32:
        Name: win32
        Python: $(Build.BinariesDirectory)\bin_$(Name)\python.exe
        PYTHONHOME: $(Build.SourcesDirectory)
      amd64:
        Name: amd64
        Python: $(Build.BinariesDirectory)\bin_$(Name)\python.exe
        PYTHONHOME: $(Build.SourcesDirectory)

  steps:
  - template: ./checkout.yml

  - task: DownloadBuildArtifacts@0
    displayName: 'Download artifact: bin_$(Name)'
    inputs:
      artifactName: bin_$(Name)
      downloadPath: $(Build.BinariesDirectory)

  - template: ./layout-command.yml

  - powershell: |
      $(LayoutCmd) --copy "$(Build.ArtifactStagingDirectory)\nuget" --preset-nuget
    displayName: 'Generate nuget layout'
    env:
      TCL_LIBRARY: $(Build.BinariesDirectory)\bin_$(Name)\tcl\tcl8

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: layout_nuget_$(Name)'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\nuget'
      ArtifactName: layout_nuget_$(Name)
